//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.ErrorLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.ErrorLocalization.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active.
        /// </summary>
        public static string AccountIsDeactive {
            get {
                return ResourceManager.GetString("AccountIsDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not found.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is duplicated.
        /// </summary>
        public static string CodeDuplicated {
            get {
                return ResourceManager.GetString("CodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and comfirm password must match.
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password field is required.
        /// </summary>
        public static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được trống.
        /// </summary>
        public static string EmtyName {
            get {
                return ResourceManager.GetString("EmtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI định dạng sai.
        /// </summary>
        public static string ErrorFormatBMI {
            get {
                return ResourceManager.GetString("ErrorFormatBMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại sức khỏe định dạnh sai.
        /// </summary>
        public static string ErrorFormatHealthGrade {
            get {
                return ResourceManager.GetString("ErrorFormatHealthGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều cao định dạng sai.
        /// </summary>
        public static string ErrorFormatHeight {
            get {
                return ResourceManager.GetString("ErrorFormatHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cân nặng định dạng sai.
        /// </summary>
        public static string ErrorFormatWeight {
            get {
                return ResourceManager.GetString("ErrorFormatWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh định dạng sai.
        /// </summary>
        public static string ErrorFormatYearOfBirth {
            get {
                return ResourceManager.GetString("ErrorFormatYearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty.
        /// </summary>
        public static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not excel file.
        /// </summary>
        public static string FileNotExcelFile {
            get {
                return ResourceManager.GetString("FileNotExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login or pin is incorrect.
        /// </summary>
        public static string Login_Device_Failed {
            get {
                return ResourceManager.GetString("Login_Device_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found a customer linked with the login account.
        /// </summary>
        public static string NotFoundCustomerLinkedWithAccount {
            get {
                return ResourceManager.GetString("NotFoundCustomerLinkedWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Can Not Contain First Name Or Last Name.
        /// </summary>
        public static string PasswordCanNotContainFirstNameOrLastName {
            get {
                return ResourceManager.GetString("PasswordCanNotContainFirstNameOrLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is not correct.
        /// </summary>
        public static string PasswordNotCorrect {
            get {
                return ResourceManager.GetString("PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Not Found.
        /// </summary>
        public static string PatientNotFound {
            get {
                return ResourceManager.GetString("PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is denied.
        /// </summary>
        public static string Permission_Denied {
            get {
                return ResourceManager.GetString("Permission_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is being assigned for account.
        /// </summary>
        public static string RoleAssigned {
            get {
                return ResourceManager.GetString("RoleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code Fail.
        /// </summary>
        public static string SendCodeFail {
            get {
                return ResourceManager.GetString("SendCodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is not from Azure AD.
        /// </summary>
        public static string TokenNotFromAzureAD {
            get {
                return ResourceManager.GetString("TokenNotFromAzureAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not verified.
        /// </summary>
        public static string VerifyNeeded {
            get {
                return ResourceManager.GetString("VerifyNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Passcode.
        /// </summary>
        public static string WrongPasscode {
            get {
                return ResourceManager.GetString("WrongPasscode", resourceCulture);
            }
        }
    }
}
